name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest # 选择最新的ubuntu系统
    steps:
      - name: Checkout
        uses: actions/checkout@master # 将代码拷贝到虚机中

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
          BRANCH: gh-pages # 存放产物的分支名称
          FOLDER: dist # 存放build后产物的目录
          BUILD_SCRIPT: npm install && npm run build # 执行的命令
